// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY4U7tchsvjY1Ck9c_4BRiH6muejJOe7E',
    appId: '1:438507125086:web:ac50369fe6d441b40037cf',
    messagingSenderId: '438507125086',
    projectId: 'chatapp-dfb66',
    authDomain: 'chatapp-dfb66.firebaseapp.com',
    storageBucket: 'chatapp-dfb66.appspot.com',
    measurementId: 'G-WWE0WHVDSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs4WRgiAmOczyKvD9rUsCsZhEAo0vzMSA',
    appId: '1:438507125086:android:5840e27c042b96790037cf',
    messagingSenderId: '438507125086',
    projectId: 'chatapp-dfb66',
    storageBucket: 'chatapp-dfb66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwWjJ2AMxUp--xHeHXSjMBoOzCOfRU2Tk',
    appId: '1:438507125086:ios:75cdf4aa7b7649e00037cf',
    messagingSenderId: '438507125086',
    projectId: 'chatapp-dfb66',
    storageBucket: 'chatapp-dfb66.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
